name: Java workflow

on:
  push:
    branches:
      - try_github_actions

env:
  NODE_VERSION: '13.x'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source tree
        uses: actions/checkout@v1
      - name: Cache Bazel artifacts
        uses: actions/cache@v2
        with:
          path: |
            ~/.cache/bazel-disk
            ~/.cache/bazel-repo
          key: ${{ runner.os }}-bazel-build-${{ hashFiles('**/BUILD.bazel') }}
          restore-keys: |
            ${{ runner.os }}-bazel-build-
      - name: Setup bazelisk
        run: |
          curl -L -o bazelisk "https://github.com/bazelbuild/bazelisk/releases/download/v1.7.4/bazelisk-linux-amd64"
          chmod +x bazelisk && sudo mv bazelisk /usr/local/bin/bazel
      - name: Setup Java
        uses: actions/setup-java@v1
        with:
          java-version: '11'
      - name: Build grid
        run: |
          sudo df -h
          java -version
          javac -version
          cp .github/.bazelrc.local .
          bazel build grid
          sudo df -h

  small_tests:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source tree
        uses: actions/checkout@v1
      - name: Cache Bazel artifacts
        uses: actions/cache@v2
        with:
          path: |
            ~/.cache/bazel-disk
            ~/.cache/bazel-repo
          key: ${{ runner.os }}-bazel-small-tests-${{ hashFiles('**/BUILD.bazel') }}
          restore-keys: |
            ${{ runner.os }}-bazel-small-tests-
            ${{ runner.os }}-bazel-build-
      - name: Setup bazelisk
        run: |
          curl -L -o bazelisk "https://github.com/bazelbuild/bazelisk/releases/download/v1.7.4/bazelisk-linux-amd64"
          chmod +x bazelisk && sudo mv bazelisk /usr/local/bin/bazel
      - name: Setup Java
        uses: actions/setup-java@v1
        with:
          java-version: '11'
      - name: Run small tests
        run: |
          sudo df -h
          cp .github/.bazelrc.local .
          bazel query "attr(size, small, tests(//java/...)) except attr(tags, lint, tests(//java/...))" | xargs bazel test
          sudo df -h

#  lint:
#    needs: build
#    runs-on: ubuntu-latest
#
#    steps:
#      - name: Checkout source tree
#        uses: actions/checkout@v1
#      - name: Cache Bazel artifacts
#        uses: actions/cache@v2
#        with:
#          path: |
#            ~/.cache/bazel-disk
#            ~/.cache/bazel-repo
#          key: ${{ runner.os }}-bazel-lint-${{ hashFiles('**/BUILD.bazel') }}
#          restore-keys: |
#            ${{ runner.os }}-bazel-lint-
#            ${{ runner.os }}-bazel-
#      - name: Setup bazelisk
#        run: |
#          curl -L -o bazelisk "https://github.com/bazelbuild/bazelisk/releases/download/v1.7.4/bazelisk-linux-amd64"
#          chmod +x bazelisk && sudo mv bazelisk /usr/local/bin/bazel
#      - name: Setup Java
#        uses: actions/setup-java@v1
#        with:
#          java-version: '11'
#      - name: Run linter
#        run: |
#          sudo df -h
#          cp .github/.bazelrc.local .
#          bazel query "attr(tags, lint, tests(//java/...))" | xargs bazel test
#          sudo df -h

  chrome_tests:
    needs: small_tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source tree
        uses: actions/checkout@v1
      - name: Cache Bazel artifacts
        uses: actions/cache@v2
        with:
          path: |
            ~/.cache/bazel-disk
            ~/.cache/bazel-repo
          key: ${{ runner.os }}-bazel-lint-${{ hashFiles('**/BUILD.bazel') }}
          restore-keys: |
            ${{ runner.os }}-bazel-lint-
            ${{ runner.os }}-bazel-build-
      - name: Setup bazelisk
        run: |
          curl -L -o bazelisk "https://github.com/bazelbuild/bazelisk/releases/download/v1.7.4/bazelisk-linux-amd64"
          chmod +x bazelisk && sudo mv bazelisk /usr/local/bin/bazel
      - name: Setup Java
        uses: actions/setup-java@v1
        with:
          java-version: '11'
      - name: Run browser tests in Chrome
        run: |
          sudo df -h
          cp .github/.bazelrc.local .
          chromedriver -version
          bazel query "attr(tags, chrome, tests(//java/client/...)) except attr(tags, remote, tests(//java/client/...))" | xargs bazel test
          sudo df -h
